---
apiVersion: v1
kind: Namespace
metadata:
  name: test-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: test-irsa
  annotations:
    eks.amazonaws.com/role-arn: "<FULL_ARN>"
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-irsa
  namespace: test-irsa
  labels:
    app: test-irsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-irsa
  template:
    metadata:
      labels:
        app: test-irsa
    spec:
      containers:
        - name: test-irsa
          image: ghcr.io/avnes/test-irsa:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
      serviceAccountName: test-sa
